language: php
php:
  - 7.1
before_script:
  - composer install --dev
script:
  - vendor/bin/phpstan analyse -l 7 src
  - vendor/bin/phpunit --coverage-clover=build/log/clover.xml
  - vendor/bin/phpcs --standard=PSR12 src