language: php
php:
  - 7.1
before_script:
  - composer install --dev
script:
  - composer stan
  - vendor/bin/phpunit --coverage-clover=build/log/clover.xml
  - composer cs
  - vendor/bin/php-coveralls -v